name: Deployment Workflow

on:
  workflow_run:
    workflows: [ 'test-master-build' ]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      ACR_LOGIN_SERVER: 'samaddyplayground.azurecr.io'
      DOCKER_IMAGE_NAME: 'playground-fastapi'
      WEB_APP_NAME: 'samaddyplayground'
      RESOURCE_GROUP_NAME: 'web-apps-rg'

    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Azure CLI script
        uses: azure/CLI@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Tag and Push Docker Image to ACR
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }} ${{ env.ACR_LOGIN_SERVER }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy Docker Image to Azure App Service
        run: |
          az webapp config container set --name ${{ env.WEB_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
          --docker-custom-image-name ${{ env.ACR_LOGIN_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
          az webapp restart --name ${{ env.WEB_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }}
